#include <math.h>
#include <time.h>
#include <stdio.h>
#include <sched.h>
#include <errno.h>
#include <stdlib.h>
#include <pthread.h>
#include <sys/time.h>
#include <sys/timeb.h>
#include <semaphore.h>
#include <sys/timerfd.h>
#include <allegro5/allegro.h>
#include <allegro5/allegro_ttf.h>
#include <allegro5/allegro_font.h>
#include <allegro5/allegro_color.h>
#include <allegro5/allegro_audio.h>
#include <allegro5/allegro_acodec.h>
#include <allegro5/allegro_primitives.h>

#include "audio.h"
#include "graph_v_c.h"
#include "periodic.c"
#include "circular_array.c"
#include "variables.h"
#include "osc_f.c"
#include "error.c"
#include "rt_attr_task.c"
#include "all_init.c"
#include "graphic.c"
#include "input_handler.c"
#include "audio.c"
#include "fdacoefs_hp_300.h"
#include "fdacoefs_lp_300.h"
#include "filter.c"