#include <pthread.h>
#include <sched.h>
#include "rt_attr_task.h"
#include "error.h"

// create attribute for joinable tasks
void init_hrt_attr(pthread_attr_t *rt_attr, struct sched_param *hrt_param, int n){
	int ctrl_var = 0;
	int policy = SCHED_RR;
	// //initialize task attribute
	ctrl_var = pthread_attr_init(rt_attr);
	error_stamp(ctrl_var, 0, "pthread_attr_init");

	// use round roibin
	ctrl_var = pthread_attr_setschedpolicy(rt_attr, policy);
	error_stamp(ctrl_var, 0, "pthread_attr_setschedpolicy");

	// set joinable
	ctrl_var = pthread_attr_setdetachstate(rt_attr, PTHREAD_CREATE_JOINABLE);
	error_stamp(ctrl_var, 0, "pthread_attr_setdetachstate");

	// set priority
	hrt_param->sched_priority = n;

	// setting the new scheduling param
	ctrl_var = pthread_attr_setschedparam(rt_attr, hrt_param);
	error_stamp(ctrl_var, 0, "pthread_setschedparam");

	// explicit sched for tasks generated by this task
	ctrl_var = pthread_attr_setinheritsched(rt_attr, PTHREAD_EXPLICIT_SCHED);
	error_stamp(ctrl_var, 0, "pthread_attr_setinheritsched");
}

// create attribute for detached tasks
void init_hrt_attr_d(pthread_attr_t *rt_attr, struct sched_param *hrt_param, int n){
	int ctrl_var = 0;
	int policy = SCHED_RR;
	// //initialize task attribute
	ctrl_var = pthread_attr_init(rt_attr);
	error_stamp(ctrl_var, 0, "pthread_attr_init");

	ctrl_var = pthread_attr_setschedpolicy(rt_attr, policy);
	error_stamp(ctrl_var, 0, "pthread_attr_setschedpolicy");

	// set detached
	ctrl_var = pthread_attr_setdetachstate(rt_attr, PTHREAD_CREATE_DETACHED);
	error_stamp(ctrl_var, 0, "pthread_attr_setdetachstate");

	hrt_param->sched_priority = n;
	/* setting the new scheduling param */
	ctrl_var = pthread_attr_setschedparam(rt_attr, hrt_param);
	error_stamp(ctrl_var, 0, "pthread_setschedparam");

	ctrl_var = pthread_attr_setinheritsched(rt_attr, PTHREAD_EXPLICIT_SCHED);
	error_stamp(ctrl_var, 0, "pthread_attr_setinheritsched");
}
